### ISSUE TITLE
Identify a way to indicate when a data site is down.

### ISSUE THREAD

**Issue by tschaffter** [nlpsandbox/nlpsandbox.io#142]
MCW is currently down. I was able to know that by asking @gkowalski, but this information would be more difficult to get by a user of the NLP Sandbox.

### Task

- [x] Create a new page on the website to report the status and history of issues related to the data sites.
- [x] Include a section to the website that indicates the status of the data site. Example:
  - Column 1: Name of the data site
  - Column 2: Status of the data site: `Running` or `Down`
- [x] Add a section that include the History of events. See [Docker Hub service status page](https://status.docker.com/pages/history/533c6539221ae15e3f000031) as an example.
- [x] Let data sites know how they must provide information about data site up/down status

**Comment by tschaffter** [comment]
Done: https://www.synapse.org/#!Synapse:syn22277123/wiki/611634
